#!/usr/bin/env node
/**
 * Vendors the shared Plan-register grammar unit and its conformance
 * corpus into a destination directory (P1-N009 child B, node P1-N011,
 * spec T3/D4, decision 1 / RU-012). The same pattern `sync_agents.ts`
 * (this node's sibling `sync_agents.py`, ported at the cutover) runs
 * for `.claude/agents/` -> `plugin/agents/`: a canonical copy here,
 * copied outward, with a "generated — do not edit here" banner and a
 * `--check` drift mode that changes nothing.
 *
 * What travels (the manifest, spec T3's "the unit and the corpus with
 * its expectations"):
 *   - plugin/scripts/lib/plan-register.ts   (the canonical unit)
 *   - plugin/scripts/lib/corpus/            (manifest, README,
 *     fixtures/, expectations/ — everything under it, recursively)
 *
 * What does not travel: plugin/scripts/lib/node-preflight.ts (local
 * tooling policy, not shared grammar — its own doc comment says so)
 * and plugin/scripts/lib/parse-output.ts / run_corpus.ts /
 * sync_shared_unit.ts itself (harness tools that invoke the Python
 * checker directly, which a vendored destination has no use for and
 * likely does not even have on its PATH).
 *
 * Banner placement, by format: `.ts` and `.md` files can carry an
 * inline "generated — do not edit here" comment, so this generator
 * inserts one (mirroring sync_agents.py's after-frontmatter
 * insertion: after the file's own leading doc comment, if it has
 * one, otherwise as the first line). `.json` and `.jsonl` files have
 * no comment syntax and are largely fixture *data* — the corpus's
 * conformance value comes from those files' bytes being exactly what
 * the checker produced, so this generator does not inject anything
 * into them. Instead a single root marker file, GENERATED.md, is
 * written at the destination naming the whole tree as generated.
 * `--check` does not rely on the banner anyway: it compares every
 * file's full content, byte for byte, against what a fresh generation
 * would produce, so a hand-edit to a JSON file is caught exactly as
 * reliably as a hand-edit to a commented one.
 *
 * Usage: sync_shared_unit.ts [--check] <destination-directory> [source-project-root]
 *   --check: exit 1 if the destination is out of sync (or missing),
 *            changing nothing. Default: vendor (create/update).
 *   destination-directory: required — this generator never guesses a
 *            consumer's layout the way sync_agents.py can guess
 *            plugin/agents/ from a project-root convention this
 *            generator does not share with a second repository.
 *   source-project-root: defaults to this repository (two directories
 *            above this file).
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { preflightNodeOrExit } from "./lib/node-preflight.ts";

preflightNodeOrExit("sync_shared_unit");

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_SOURCE_ROOT = path.resolve(HERE, "..", "..");

const BANNER_TS =
  "// Generated by sync_shared_unit.ts — do not edit here; edit the\n" +
  "// primary copy in majodali/project-orchestrator and re-run.\n";
const BANNER_MD =
  "<!-- Generated by sync_shared_unit.ts — do not edit here; edit the\n" +
  "     primary copy in majodali/project-orchestrator and re-run. -->\n";
const GENERATED_MD =
  "# Generated — do not edit this directory\n\n" +
  "Everything under this directory was copied by `sync_shared_unit.ts` " +
  "from `plugin/scripts/lib/` in majodali/project-orchestrator (P1-N009, " +
  "decision 1 / RU-012): `plan-register.ts`, the canonical Plan-register " +
  "grammar and lifecycle-stage-vocabulary unit, and `corpus/`, the " +
  "conformance corpus it travels with (spec T3).\n\n" +
  "`.ts` and `.md` files under this tree carry their own " +
  '"generated — do not edit here" comment; `.json`/`.jsonl` fixture ' +
  "and expectation files have no comment syntax to carry one in, so " +
  "this file is their marker instead. Re-run the generator's `--check` " +
  "mode to confirm nothing here has drifted from the primary copy.\n";

/** Files (by relative path from the source's lib/ directory) that
 * make up the travelling set. Explicit, not a directory sweep of
 * lib/ — node-preflight.ts and parse-output.ts live alongside the
 * unit but are not part of what a consumer needs. */
function travellingSet(
  sourceRoot: string,
): Array<{ rel: string; abs: string }> {
  const libDir = path.join(sourceRoot, "plugin", "scripts", "lib");
  const entries: Array<{ rel: string; abs: string }> = [];
  entries.push({
    rel: "plan-register.ts",
    abs: path.join(libDir, "plan-register.ts"),
  });

  const corpusDir = path.join(libDir, "corpus");
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const abs = path.join(dir, name);
      const rel = path.join("corpus", path.relative(corpusDir, abs));
      if (statSync(abs).isDirectory()) {
        walk(abs);
      } else {
        entries.push({ rel, abs });
      }
    }
  };
  walk(corpusDir);
  return entries;
}

function bannerFor(rel: string): string | null {
  if (rel.endsWith(".ts")) return BANNER_TS;
  if (rel.endsWith(".md")) return BANNER_MD;
  return null;
}

/** Inserts the banner after a leading `/** ... *\/` doc comment for
 * `.ts` files (mirroring sync_agents.py's after-frontmatter
 * insertion), or after a leading `# Title` line for `.md` files;
 * otherwise prepends it. */
function withBanner(content: string, rel: string): string {
  const banner = bannerFor(rel);
  if (!banner) return content;

  if (rel.endsWith(".ts")) {
    const m = /^\/\*\*[\s\S]*?\*\/\n/.exec(content);
    if (m) {
      return (
        content.slice(0, m[0].length) +
        "\n" +
        banner +
        content.slice(m[0].length)
      );
    }
    return banner + "\n" + content;
  }

  // .md: insert after the first line if it looks like a title.
  const lines = content.split("\n");
  if (lines[0]?.startsWith("#")) {
    return [lines[0], "", banner.trimEnd(), ...lines.slice(1)].join("\n");
  }
  return banner + "\n" + content;
}

function expectedFiles(sourceRoot: string): Map<string, string> {
  const expected = new Map<string, string>();
  for (const { rel, abs } of travellingSet(sourceRoot)) {
    const content = readFileSync(abs, "utf-8");
    expected.set(rel, withBanner(content, rel));
  }
  expected.set("GENERATED.md", GENERATED_MD);
  return expected;
}

function currentFiles(destRoot: string): Map<string, string> {
  const current = new Map<string, string>();
  if (!existsSync(destRoot)) return current;
  const walk = (dir: string, relDir: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const abs = path.join(dir, name);
      const rel = relDir ? path.join(relDir, name) : name;
      if (statSync(abs).isDirectory()) {
        walk(abs, rel);
      } else {
        current.set(rel, readFileSync(abs, "utf-8"));
      }
    }
  };
  walk(destRoot, "");
  return current;
}

function diffKeys(
  expected: Map<string, string>,
  current: Map<string, string>,
): string[] {
  const drift = new Set<string>();
  for (const [rel, content] of expected) {
    if (current.get(rel) !== content) drift.add(rel);
  }
  for (const rel of current.keys()) {
    if (!expected.has(rel)) drift.add(rel);
  }
  return [...drift].sort();
}

function main(): number {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const positionals = args.filter((a) => a !== "--check");
  const destArg = positionals[0];
  if (!destArg) {
    console.error(
      "sync_shared_unit: a destination directory is required. " +
        "Usage: sync_shared_unit.ts [--check] <destination-directory> [source-project-root]",
    );
    return 1;
  }
  const destRoot = path.resolve(destArg);
  const sourceRoot = positionals[1]
    ? path.resolve(positionals[1])
    : DEFAULT_SOURCE_ROOT;

  if (
    !existsSync(
      path.join(sourceRoot, "plugin", "scripts", "lib", "plan-register.ts"),
    )
  ) {
    console.error(
      `sync_shared_unit: no plugin/scripts/lib/plan-register.ts under ${sourceRoot}.`,
    );
    return 1;
  }

  const expected = expectedFiles(sourceRoot);
  const current = currentFiles(destRoot);
  const drift = diffKeys(expected, current);

  if (drift.length === 0) {
    console.log(
      `sync_shared_unit: in sync (${expected.size} file(s) at ${destRoot}).`,
    );
    return 0;
  }

  if (check) {
    console.log(`sync_shared_unit: OUT OF SYNC: ${drift.join(", ")}`);
    return 1;
  }

  // Vendor: remove anything under destRoot not in `expected`, then
  // write every expected file (creating directories as needed).
  if (existsSync(destRoot)) {
    for (const rel of current.keys()) {
      if (!expected.has(rel)) rmSync(path.join(destRoot, rel));
    }
  }
  for (const [rel, content] of expected) {
    const abs = path.join(destRoot, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
  console.log(
    `sync_shared_unit: vendored ${expected.size} file(s) to ${destRoot}.`,
  );
  return 0;
}

process.exit(main());
